server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xianshun163/config-repo.git #git@github.com:xianshun163/config-repo.git  #
          search-paths: config-repo
      username: xianshun163@163.com
      password: xianshun111
      label: master
  application:
    name: config-server
    
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
foo:
  db: xs22    